[package]
name = "hexcede/rollback"
description = "Very simple utility for producing reversible mutations"
authors = ["Hexcede"]
version = "0.0.0"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
